<?php

use \Drupal\campaignion\ContactTypeManager;
use \Drupal\campaignion\NoEmailException;
use \Drupal\campaignion\CRM\Import\Source\ArraySource;
use \Drupal\little_helpers\Services\Container;
use \Drupal\little_helpers\Webform\Submission;
use \Drupal\webform_paymethod_select\WebformPaymentContext;

use \Drupal\campaignion_logcrm\Client;
use \Drupal\campaignion_logcrm\Event;
use \Drupal\campaignion_logcrm\OptInExporter;
use \Drupal\campaignion_logcrm\PaymentExporter;
use \Drupal\campaignion_logcrm\QueueItem;
use \Drupal\campaignion_logcrm\SubmissionExporter;

if (module_exists('manual_direct_debit_uk')) {
  require_once 'integrations/manual_direct_debit_uk.inc';
}
if (module_exists('paypal_payment')) {
  require_once 'integrations/paypal_payment.inc';
}
if (module_exists('webform_paymethod_select')) {
  require_once 'integrations/webform_paymethod_select.inc';
}
if (module_exists('campaignion_supporter_tags')) {
  require_once 'integrations/campaignion_supporter_tags.inc';
}
if (module_exists('campaignion_source_tags')) {
  require_once 'integrations/campaignion_source_tags.inc';
}

/**
 * Implements hook_cronapi().
 */
function campaignion_logcrm_cronapi($op, $job = NULL) {
  $items['campaignion_logcrm_send_queue'] = array(
    'description' => 'Send queue data to logcrm',
    'rule' => '*/2 * * * *',
    'weight' => 100,
    'file' => 'cron.php',
    'callback' => '\\Drupal\\campaignion_logcrm\\send_queue',
  );
  return $items;
}

/**
 * Implements hook_libraries_info().
 */
function campaignion_logcrm_libraries_info() {
  $libraries['dflydev-hawk'] = [
    'name' => 'Hawk — A PHP Implementation',
    'vendor url' => 'https://github.com/dflydev/dflydev-hawk',
    'download url' => 'https://github.com/dflydev/dflydev-hawk',
    'version' => '0.0.0',
    'xautoload' => function($adapter) {
       $adapter->composerJson('composer.json');
    },
    'dependencies' => ['RandomLib (>=1.0)'],
  ];
  $libraries['RandomLib'] = [
    'name' => 'RandomLib — A library for generating random numbers and strings of various strengths.',
    'vendor url' => 'https://github.com/ircmaxell/RandomLib',
    'download url' => 'https://github.com/ircmaxell/RandomLib',
    'version' => '1.1.0',
    'xautoload' => function($adapter) {
       $adapter->composerJson('composer.json');
    },
    'dependencies' => ['SecurityLib (>=1.1)'],
  ];
  $libraries['SecurityLib'] = [
    'name' => 'SecurityLib',
    'vendor url' => 'https://github.com/ircmaxell/SecurityLib',
    'download url' => 'https://github.com/ircmaxell/SecurityLib',
    'version' => '1.1.0',
    'xautoload' => function($adapter) {
       $adapter->composerJson('composer.json');
    },
  ];
  return $libraries;
}

/**
 * Implements hook_little_helpers_serices().
 */
function campaignion_logcrm_little_helpers_services() {
  $info['campaignion_logcrm.client'] = [
    'class' => Client::class,
    'constructor' => 'fromConfig',
    'arguments' => ['!campaignion_logcrm_credentials'],
  ];
  $info['campaignion_logcrm.component_plugins'] = [
    'class' => Container::class,
    'arguments' => ['campaignion_logcrm.component_plugins'],
    'calls' => [
      ['loadSpecsFromHook', [
        'campaignion_logcrm_webform_component_exporter_info',
      ]],
    ],
  ];
  $info['campaignion_logcrm.opt_in_exporter'] = [
    'class' => OptInExporter::class,
    'constructor' => 'fromConfig',
  ];
  $info['campaignion_logcrm.payment_exporter']['class'] = PaymentExporter::class;
  $info['campaignion_logcrm.submission_exporter'] = [
    'class' => SubmissionExporter::class,
    'arguments' => [
      '@campaignion_logcrm.component_plugins',
      '@campaignion_logcrm.opt_in_exporter',
    ],
  ];
  return $info;
}

/**
 * Implements hook_xmlrpc().
 */
function campaignion_logcrm_xmlrpc() {
  $callbacks[] = [
    'campaignion.logcrm.post_event',
    'campaignion_logcrm_post_event',
    ['struct', 'string', 'string'], // event JSON and signature.
    t('Post JSON dumps to be imported by campaignion'),
  ];
  return $callbacks;
}

/**
 * Import a JSON dump into campaignions contacts.
 */
function campaignion_logcrm_post_event($event, $signature) {
  $c = variable_get('campaignion_logcrm_credentials', []);
  if (!isset($c['secret_key'])) {
    return (object) ['code' => 401, 'message' => 'No secret key configured'];
  }
  if (hash_hmac('sha256', $event, $c['secret_key']) != $signature) {
    return (object) ['code' => 401, 'message' => 'Unauthorized'];
  }
  $data = drupal_json_decode($event);
  if (!is_array($data)) {
    return (object) ['code' => 400, 'message' => 'Event must be a JSON object'];
  }

  $importer = ContactTypeManager::instance()->importer('campaignion_logcrm');
  $source = new ArraySource($data);
  try {
    $contact = $importer->findOrCreateContact($source);
    if ($importer->import($source, $contact)) {
      $contact->save();
      return (object) ['code' => 200,  'message' => 'Contact saved.'];
    }
    return (object) ['code' => 200,  'message' => 'Contact unchanged.'];
  }
  catch (NoEmailException $e) {
    return (object) ['code' => 404, 'message' => 'Missing email in record.'];
  }
}

/**
 * Implements hook_webform_submission_insert().
 */
function campaignion_logcrm_webform_submission_insert($node, $submission) {
  // Send submission event.
  $e = Event::fromSubmission(new Submission($node, $submission));
  QueueItem::byData([
    'type' => 'webform_submission',
    'id' => $submission->sid,
    'event' => $e,
  ])->save();
}

/**
 * Implements hook_webform_submission_update().
 */
function campaignion_logcrm_webform_submission_update($node, $submission) {
  campaignion_logcrm_webform_submission_insert($node, $submission);
}

/**
 * Implements hook_webform_confirm_email_email_confirmed().
 */
function campaignion_logcrm_webform_confirm_email_email_confirmed($node, $submission) {
  QueueItem::byData([
    'type' => 'webform_submission_confirmed',
    'id' => $submission->sid,
    'event' => Event::fromSubmissionConfirmation(new Submission($node, $submission)),
  ])->save();
}

/**
 * Implements hook_payment_status_change().
 */
function campaignion_logcrm_payment_status_change(Payment $payment, PaymentStatusItem $previous_status_item) {
  $statusChangedToSuccess = $payment->getStatus()->status == PAYMENT_STATUS_SUCCESS && $previous_status_item->status != PAYMENT_STATUS_SUCCESS;
  $hasContextObj = $payment->contextObj instanceof WebformPaymentContext;
  if (!$statusChangedToSuccess || !$hasContextObj)
    return;
  // Send payment event.
  $e = Event::fromPayment($payment);
  QueueItem::byData([
    'type' => 'payment',
    'id' => $payment->pid,
    'event' => $e,
  ])->save();
}

/**
 * Implements hook_campaignion_logcrm_webform_component_exporter_info().
 */
function campaignion_logcrm_campaignion_logcrm_webform_component_exporter_info() {
  $ns = '\\Drupal\\campaignion_logcrm\\WebformComponent\\';
  $info['select'] = $ns . 'Select';
  $info['verbatim'] = $ns . 'Verbatim';
  return $info;
}
